### PR TITLE
Do not override os-table overflow setting

### PR DESCRIPTION
**Pull request by RoyEJohnson**
For: https://github.com/openstax/unified/issues/1959
(Issue #1)

### CODE REVIEW

**Comment by RoyEJohnson** [comment]
This seems to have broken the test of the first `EXPECTED_SCROLL_TOPS` IN `[Content.browserspec.tsx](https://github.com/openstax/rex-web/blob/a93b5941d75d6afbaa36161a9021a49d1b42973b/src/app/content/components/Content.browserspec.tsx#L13)`, both for Desktop and Mobile. The returned numbers are higher than expected:
```
FAIL src/app/content/components/Content.browserspec.tsx (8.767 s)
  ● Content › Desktop › scrolls correctly to all elements

    expect(received).toEqual(expected) // deep equality

    Expected: 242
    Received: 312

      42 |           // Loading page with anchor
      43 |           const anchorScrollTop = await page.evaluate('document.documentElement.scrollTop');
    > 44 |           expect(anchorScrollTop).toEqual(expectedScrollTops[0]);
         |                                   ^
      45 |         }
      46 |
      47 |         // Clicking links

      at Object.<anonymous> (src/app/content/components/Content.browserspec.tsx:44:35)
          at runMicrotasks (<anonymous>)

  ● Content › Mobile › scrolls correctly to all elements

    expect(received).toEqual(expected) // deep equality

    Expected: 239
    Received: 295

      42 |           // Loading page with anchor
      43 |           const anchorScrollTop = await page.evaluate('document.documentElement.scrollTop');
    > 44 |           expect(anchorScrollTop).toEqual(expectedScrollTops[0]);
         |                                   ^
      45 |         }
      46 |
      47 |         // Clicking links

      at Object.<anonymous> (src/app/content/components/Content.browserspec.tsx:44:35)
```

**Review by jivey — COMMENTED** [review]
Is the scroll top testing a page that includes an os-table? At a glance I'm not sure why that rule change should change the scroll top

**Comment by RoyEJohnson** [comment]
It seems like it must be adding scrollbars to some tables. If scrollbars are 14px high, there are 5 and 4 scrollbars being added, respectively.

**Review by jivey — CHANGES_REQUESTED** [review]
I think we need to adjust the rule for this... digging into the rendered test page to figure out the scroll failure, I saw some overflows in unexpected places:

Screenshot 2023-07-06 at 8 56 05 PM
Screenshot 2023-07-06 at 8 56 17 PM

You can see the page it is testing against by running `yarn start:static` and it should be available at `/books/book-slug-1/pages/test-page-for-generic-styles#term103`

Maybe we can target the table itself for the overflow rule? Though there might be a specificity issue.

**Comment by RoyEJohnson** [comment]
I have made a ce-styles PR to address this for `[data-type="exercise-question"]`

**Pull request closed without merging**
