### PR TITLE
Add canonical maps for the old econ editions and the new macro/micro

### PR DESCRIPTION
**Pull request by Dantemss**
For: https://github.com/openstax/unified/issues/2100
I added maps for macro/micro 3e to econ 3e but 2e didn't have that so now I'm wondering...

### CODE REVIEW

**Review by TomWoodward — COMMENTED** [review]
its not necessarily a problem, but its a little confusing that some of the econ books are in these separate files and others are listed directly in https://github.com/openstax/rex-web/blob/dabb223e0adcee93bd1978e9744f7a4b5ecfa262/src/canonicalBookMap.ts

**Comment by Dantemss** [comment]
Maybe this is causing the test failure? Because now that I look at it, those books being in that other file means I added some duplicates. I'll remove/move them and see if things improve.

**Comment by Dantemss** [comment]
OK I moved them and replaced a couple of the ones I had added since they'll chain anyway.

**Comment by Dantemss** [comment]
Checked micro 3e, micro 2e and econ 2e on Heroku and they all link to econ 3e.

**Review by TomWoodward — APPROVED** [review]

**Pull request merged**
