### PR TITLE
Add proxy config for archive

### PR DESCRIPTION
**Pull request by TomWoodward**

### CODE REVIEW

**Comment by philschatz** [comment]
Could jenkins be failing because `yarn build` did not run?

**Comment by philschatz** [comment]
Oh, it seems to be erroring because `yarn server` takes an additional argument... the `port` number to start up as. See #18

**Comment by TomWoodward** [comment]
jenkins was failing because the tests weren't stable until the screenshot tests pr was merged

**Comment by TomWoodward** [comment]
jenkins file system access is _very slow_ so i upped the timeouts, travis was actually passing before that.

**Review by philschatz — APPROVED** [review]

**Pull request merged**
