### PR TITLE
Restrict images in figures to context text width

### PR DESCRIPTION
**Pull request by RoyEJohnson**
For: https://github.com/openstax/unified/issues/2673

### CODE REVIEW

**Review by TomWoodward — CHANGES_REQUESTED** [review]
styling content should be done in the content styles (ideally the baked styles in cnx-recipes, but also for now in the rex content `.less` files) and why does the need an explicit width to make it work? shouldn't it be responsive?

**Comment by RoyEJohnson** [comment]
The attribute width is something Chrome/lightouse wants for layout efficiency.
The issue being solved is a weird glitch: before the image is loaded, the attribute width is respected, causing the horizontal overflow. After the image loads, the image is a reasonable size and the overflow goes away.
I'll see if I can make the change in the .less file. There is also a change being made in recipes, I think.

**Comment by TomWoodward** [comment]
if i change the `figure img` to be `width: 100%;` instead of `max-width: 100%` i think its behaving better, do you see that as well?

**Comment by RoyEJohnson** [comment]
Yes, that works for me.

**Comment by RoyEJohnson** [comment]
Does that mean it is a change that should be made on the Content side?

**Comment by TomWoodward** [comment]
i tried testing it on a figure image that was more narrow and it still seemed to look right, but i would appreciate some more verification. and yes the change would be in both the rex `.less` files (for non-baked style books) and in cnx-recipes (for most books)

**Review by TomWoodward — APPROVED** [review]
there is a page later in the book that beth linked that has some smaller image figures and they all look fine, i think this is ok 

https://rex-web-another-shot-at-zq8b9b.herokuapp.com/books/workplace-software-skills@c795d5f/pages/1-1-computing-from-inception-to-today?archive=https%3A%2F%2Fopenstax.org%2Fapps%2Farchive-preview%2F20231109.173216

note that we also need to make the change in cnx-recipes before we can close the parent issue

**Comment by RoyEJohnson** [comment]
cnx-recipes, not ce-styles? Is that why my attempt to do it in ce-styles didn't seem to work?

**Comment by TomWoodward** [comment]
i thought the styles were here https://github.com/openstax/cnx-recipes/blob/main/styles/books/generic/webview.scss but they might have moved to a new repo at some point.

**Pull request merged**
