### PR TITLE
world history vol 1 updates

### PR DESCRIPTION
**Pull request by staxbot**
for: https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/2342

### CODE REVIEW

**Review by theresamasciale — APPROVED** [review]

**Comment by Malar-Natarajan** [comment]
@theresamasciale what book is this?

**Comment by theresamasciale** [comment]
@Malar-Natarajan This is world history volume 1. Volume 2 was already on the ABL but i added this in to make it in time to for it's 4/19 pub date

**Comment by ewaforman** [comment]
Looks good in dev. Only one thing: 

1. Useless dot in caption under map (all maps in section): 
https://drive.google.com/file/d/13OJnMuoLypNNE2R3fJ0r9sByaDnP98OI/view?usp=sharing

**Comment by Malar-Natarajan** [comment]
I think that is fine @ewaforman so I merged it.

**Pull request merged**
