### PR TITLE
chore: code climate

### PR DESCRIPTION
**Pull request by TomWoodward**
check out the dashboard here https://codeclimate.com/github/openstax/rex-web

pretty sure their opinion of us will improve when they have a code coverage baseline on master

we can also use [integrations](https://docs.codeclimate.com/docs/github-pull-requests) notify us about the types of things in the `Repository stats` section of that dashboard on pull requests. its easy to disregard many of those issues as irritants especially the ones in the test files, but it seems undeniable that fixing them would ease maintenance and understanding for new devs.

### CODE REVIEW

**Review by philschatz — DISMISSED** [review]
❤️ . Did you turn on the integration 4 hours ago?

**Comment by TomWoodward** [comment]
about 4 hours ago according to when the initial master build was

**Review by philschatz — COMMENTED** [review]
Just suggesting that adding a shields.io badge to the readme might help in getting a link to the code climate report

**Comment by TomWoodward** [comment]
the codeclimate shields appear broken https://github.com/badges/shields/issues/1518

**Pull request merged**
