### PR TITLE
FE playwright test: close osano to fix failures

### PR DESCRIPTION
**Pull request by Malar-Natarajan**
for: https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/2633

1. close the osano cookie management popup on opening the application
2. change the keyboard navigation tests to desktop only

### CODE REVIEW

**Comment by Malar-Natarajan** [comment]
@gregfitch this is the PR that fails with safari (only in CI). In my local it passes all the time. There is a new widget (osano cookie management) that pops up in the bottom of a page when we open a rex page in a new session. I am trying to get rid of it. 
Any advice for this CI failure

**Comment by gregfitch** [comment]
What is the error message from the CI test? Are you able to get a trace from the run?

**Comment by Malar-Natarajan** [comment]
> What is the error message from the CI test? Are you able to get a trace from the run?

The traces are in the playwright runs. https://github.com/openstax/rex-web/actions/runs/6279114394?pr=2035
Do you have any idea about which geo location does saucelabs run the tests? The osano widget displays different buttons differently in different screens based on US states. I think this is also causing problem sometimes. But safari failing all the time, I dont know why

**Comment by gregfitch** [comment]
I would set it instead. https://docs.saucelabs.com/dev/test-configuration-options/#timezone

**Comment by Malar-Natarajan** [comment]
@gregfitch I tried setting locale, timezone, geo location in 3 different pr's and those did not help.

I tried using the If block to click either `accept` or `close` buttons depending on which popup message appears. And
the CI worked couple of times with both the messages.
[handling the message when close button is visible](https://github.com/openstax/rex-web/actions/runs/6499100248/job/17654306587)
[handling the message when accept button is visible](https://github.com/openstax/rex-web/actions/runs/6509716141/job/17681823458)

I just deleted few unused code and now safari fails again. Now I cant decide if its safari or my code or something else

**Review by gregfitch — APPROVED** [review]

**Pull request merged**
