### PR TITLE
osano direct install

### PR DESCRIPTION
**Pull request by TomWoodward**
for: openstax/unified#2425

i was trying to figure out how to make this work via GTM, but then i saw [this](https://docs.osano.com/osano-and-google-tag-manager)

> Please be aware that in order for Osano's obligations under the [“No fines, No penalties” pledge](https://www.osano.com/pledge) (Section 4.7 of the Enterprise Terms of Service - Reimbursement of Regulatory Fines or Penalties) to apply, you must use the Direct Install method (in accordance with the documentation on this page) and be on the most up-to-date version of Osano CMP.

so i guess we're gonna do it this way. it'll be easier on the gtm config anyway. we just need to make sure to install it separately in every app

### CODE REVIEW

**Review by Dantemss — APPROVED** [review]
Cool, I may need to add this to the list of ignored requests in my book-scan PR (unless we have a reason to run the osano script there).

**Comment by TomWoodward** [comment]
> Cool, I may need to add this to the list of ignored requests in my book-scan PR (unless we have a reason to run the osano script there).

It should probably be blocked. If you merge yours first I can update that

**Comment by TomWoodward** [comment]
@Dantemss can you look at this again? i blocked osano in the book scan and added the footer link

**Comment by TomWoodward** [comment]
@theresamasciale you can ignore this. it tagged you because i accidentally made changes to the content configs, but i've removed the changes

**Review by Dantemss — APPROVED** [review]

**Comment by Dantemss** [comment]
Changed LGTM

**Pull request merged**
