### PR TITLE
Contemporary Mathematics updates

### PR DESCRIPTION
**Pull request by staxbot**
for: https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/2284

### CODE REVIEW

**Review by theresamasciale — APPROVED** [review]

**Comment by ewaforman** [comment]
Tested in https://rex-web-update-content--jtpxxa.herokuapp.com. Some editorial things to check. 

https://drive.google.com/file/d/1Y84YomVtuFkWmuxEsu3T3Nv5eeUxq4-a/view?usp=sharing
https://drive.google.com/file/d/1_UrYa_2TUCB0nq8WjdI4-8Ij79-Cptew/view?usp=sharing
https://drive.google.com/file/d/1Fga3L0rMhGORUwCEq5MBKzMUV0DrmxNB/view?usp=sharing
https://drive.google.com/file/d/1AOqZ7Za-GMd1pTLrdDyx6ds77rYOC5yB/view?usp=sharing
https://drive.google.com/file/d/1HwU3DCtrwL4_x8ON9lDjrcwnCtTL4by0/view?usp=sharing
https://drive.google.com/file/d/1s4mBgu8fubYWqB2HgfPu1dW6HdfxwLQV/view?usp=sharing
https://drive.google.com/file/d/1a7kkp4tkYngOuv28LYA2Gtj_NFsy968x/view?usp=sharing
https://drive.google.com/file/d/1cWkr79d5FfIzM7-5AP9jBMMGTUKO6xs8/view?usp=sharing
https://drive.google.com/file/d/1RXuteG0OhC908Q9mB0BzbtfkwBJq8rD2/view?usp=sharing
https://drive.google.com/file/d/1DA6Y9S0pZVSnUbPwCDwI7S3SGnw6NxL5/view?usp=sharing
https://drive.google.com/file/d/1TgNWI8m1rlvhu6G03ek7Bq4LwHQ3jFaZ/view?usp=sharing
https://drive.google.com/file/d/1-wFvEVMdBPFBDnh9efm_IJK-W035il0e/view?usp=sharing
https://drive.google.com/file/d/1Psr7aOeeRYloLXVG-uOHuKu2h2Dlc-tl/view?usp=sharing
https://drive.google.com/file/d/1KHO-mGBNLmTYaxjwm9Ws5mgySc5hRc7N/view?usp=sharing
https://drive.google.com/file/d/1KMc2h2lU4FgWU9cUla0jJxxJsiXN7mBv/view?usp=sharing
https://drive.google.com/file/d/19xQcZyD1WJR6xzHxYD7BFQCzwozSXAB6/view?usp=sharing
https://drive.google.com/file/d/1kjms4ONBIogo7C4oWFaAQbTDMQJZbjgF/view?usp=sharing
https://drive.google.com/file/d/1UzRMABnG-5MyyicNqnEM65CYtdOnAKVq/view?usp=sharing
https://drive.google.com/file/d/1AqK3oEJmXCn69bcmoxjujEP26dX4icFc/view?usp=sharing
https://drive.google.com/file/d/1smXp8uz-fFkkPut11-7QnDpNMwTBKOEw/view?usp=sharing
https://drive.google.com/file/d/1_uzWdZb7oTygEQ9Yscnt93fNt4BvFLnG/view?usp=sharing
https://drive.google.com/file/d/1opo09kz9Z_uHaSzQckjYkZGBDo8jif2M/view?usp=sharing
https://drive.google.com/file/d/199PnN9h5Qn-Nel_yB14FL0IsGm7l6s7V/view?usp=sharing
https://drive.google.com/file/d/19ebRjo-_o52AtMMVIyguiS4ZPSv3Mxac/view?usp=sharing
https://drive.google.com/file/d/1pZHNneO3rvfrYSBSE56S0dnm7NxIdMYp/view?usp=sharing
https://drive.google.com/file/d/1hbOA0IbO2a4VAn-WjnMP0wbuZNnXo-C8/view?usp=sharing
https://drive.google.com/file/d/1ZzIyC1Dq2xbPmCn4bzRjhvXOLM8yFpZg/view?usp=sharing
https://drive.google.com/file/d/14oIb7cYreE-i9nNNvuNEWyccsJbZlSp-/view?usp=sharing
https://drive.google.com/file/d/1tMhOCrCOspDhRhD0AxeBCjTwM0X0gdRw/view?usp=sharing
https://drive.google.com/file/d/1JrdkbVinyvumZ-sVKpnjmWLMDAcUU8BG/view?usp=sharing
https://drive.google.com/file/d/1Bs4tg7MXQmDaVDdrsTNkhpGSxrW31aCW/view?usp=sharing
https://drive.google.com/file/d/1wE1L3cOCduIf9B-PVeKhjEO8TSHnUy9J/view?usp=sharing

**Comment by Malar-Natarajan** [comment]
@theresamasciale Ewa found some content issues with the Contemprary Math book while testing. Do you want to give a quick look on these?

**Comment by openstaxalina** [comment]
Thank you, @ewaforman ! 

I spoke with @theresamasciale and @lwtchu -- we don't consider these showstoppers for release, but we want to fix them (some in content, some in code) in April. So there will be 1 or 2 updates to this title in the April releases @erikayvonne 

Can discuss further on tomorrow's call

**Comment by ewaforman** [comment]
Works good in staging (Chrome, Firefox, Edge).

**Comment by theresamasciale** [comment]
just as an update for our future reference: i fixed all issues noted in numbers 1 and 4 of Ewa's comment. 2 and 3 should be corrected in time. Thanks so much again Ewa for catching these!!!

**Pull request merged**
