### PR TITLE
upgrade sentry and add sampling config for performance traces

### PR DESCRIPTION
**Pull request by TomWoodward**
for: openstax/unified#1471

### CODE REVIEW

**Comment by jarosik10** [comment]
@TomWoodward
How can I test it?

**Comment by TomWoodward** [comment]
@jarosik10 are you able to log into https://sentry.io/organizations/openstax/issues/?project=5538506 ?

**Comment by jarosik10** [comment]
@TomWoodward Yes.

**Comment by jarosik10** [comment]
The sentry is receiving the errors. It looks like everything is fine.

**Review by jarosik10 — APPROVED** [review]

**Pull request merged**
