### PR TITLE
Fizyka dla szkół wyższych. Tom 3 updates

### PR DESCRIPTION
**Pull request by staxbot**
for: openstax/unified#1863

### CODE REVIEW

**Comment by TomWoodward** [comment]
@bethshook it looks like this one has a title change but no redirect was added, can you look into it?

**Comment by bethshook** [comment]
@TomWoodward I don't understand - isn't this book new to rex?

**Comment by TomWoodward** [comment]
I'm not seeing what I was seeing earlier, maybe I commented on the wrong book, I'll look later

**Comment by TomWoodward** [comment]
its this one https://github.com/openstax/rex-web/pull/1426

**Review by TomWoodward — CHANGES_REQUESTED** [review]
awaiting katalyst qa

**Review by TomWoodward — APPROVED** [review]

**Pull request merged**
