### PR TITLE
Add labs-cta component

### PR DESCRIPTION
**Pull request by jarosik10**
for: https://github.com/openstax/unified/issues/1628

### CODE REVIEW

**Comment by TomWoodward** [comment]
there is already a pr for this but it needs some help. jp made the backend and plugged some stuff into the FE but didn't really know what he was doing. i think there is also something going on with swagger bindings that i'll want to look at

**Review by jivey — APPROVED** [review]
My knowledge of Redux isn't the best, but this looks good to me, and the variants look right in local testing. The only thing I wasn't sure about is how the practiceQuestions feature flag changes are related, maybe that was part of the scoped work though.

**Comment by jivey** [comment]
In case it's helpful, I noticed the Selenium test seems to be failing from a hardcoded path https://github.com/openstax/rex-web/blob/master/pytest-selenium/utils/utility.py#L214

**Comment by Malar-Natarajan** [comment]
> In case it's helpful, I noticed the Selenium test seems to be failing from a hardcoded path https://github.com/openstax/rex-web/blob/master/pytest-selenium/utils/utility.py#L214

yes...its my bad. I will update it

**Review by TomWoodward — APPROVED** [review]

**Pull request merged**
