### PR TITLE
Issue 1529 - search results panel colors

### PR DESCRIPTION
**Pull request by bethshook**
for: openstax/unified#1529

### CODE REVIEW

**Comment by TomWoodward** [comment]
your changes look fine, unit tests are failing because of the react snapshots, run `yarn test:unit -u` to update them, and in your description you're missing a colon `for: link`

i know there is a trend of naming PRs with just the issue number, but i find it tedious to have to click through every time i look at a pr, i'd rather have a descriptive PR title

**Review by PiotrKozlowski — CHANGES_REQUESTED** [review]
Looks good except for the failing test. `yarn test:unit -u` will not work because `test:unit` script ends with ` && ./script/push-codecov.bash` so the `-u` parameter will be passed to the script and not to the `jest`
In order to update snapshot you have to remove ` && ./script/push-codecov.bash`, then run `yarn test:unit -u` and add ` && ./script/push-codecov.bash` again to the script.
We have to fix this in separate pr

**Comment by TomWoodward** [comment]
Oh I thought we fixed that already, we should fix that

**Comment by TomWoodward** [comment]
fixes the scripts thing https://github.com/openstax/rex-web/pull/1146

**Review by PiotrKozlowski — APPROVED** [review]

**Comment by bethshook** [comment]
this is still failing the description check for some reason, as well as a selenium test

**Comment by TomWoodward** [comment]
i updated the link for you, and selenium has been flaky recently so it isn't required to pass right now

**Pull request merged**
