### PR TITLE
Attempt to make Heroku use node 14

### PR DESCRIPTION
**Pull request by Dantemss**
For: https://github.com/openstax/unified/issues/2126

I considered Node 16 but we should probably do that when we are ready to switch `.nvmrc` as well.

Which maybe we could just do right now, I think Node 16 just works for Rex.

### CODE REVIEW

**Comment by Dantemss** [comment]
I unchecked the card so we can delay merging until the current release is locked (the code here doesn't affect the build but merging would cause a new search build which takes a while).

**Comment by Dantemss** [comment]
Nvm, commented on the wrong PR.

**Comment by Dantemss** [comment]
Heroku deployment seems to have worked, and is running Node 14.

**Review by jivey — APPROVED** [review]
For what it's worth, I've been using 16 with rex for a while and haven't seen issues. One other reason to consider it sooner too is that 2023-04-30 is end of life for 14 (https://github.com/nodejs/release#release-schedule).

**Pull request merged**
