### PR TITLE
Send nudged event to event capture as well as GA

### PR DESCRIPTION
**Pull request by Dantemss**
For: https://github.com/openstax/unified/issues/1439

### CODE REVIEW

**Comment by Dantemss** [comment]
Pinging @reedstrm to make sure I used the event correctly.

**Comment by Dantemss** [comment]
For reference, when hasStudyGuides is true, the message says:
```
Boost your studies with expert-created study guides and highlighting. <strong>It's all free.</strong>
```

and when it's false, it says:

```
Highlight, take notes, and make your own study guides. <strong>It's all free.</strong>
```

**Review by reedstrm — COMMENTED** [review]
I think this all looks good, though we haven't actually had any "nudge" events recorded yet. I'll get a sandbox deploy up so we can test against it.

**Comment by Dantemss** [comment]
Tom said the app should be Rex and since the target already tells us about highlights vs study_guides I'll just change the app to always be "rex"

**Review by jivey — APPROVED** [review]
Code change looks good to me, I'll leave it to @reedstrm if this is working for the use case

**Comment by TomWoodward** [comment]
@reedstrm i believe we're waiting on you to verify the data being reported is what you want before merging this

**Comment by reedstrm** [comment]
Ok I'll review.

**Review by reedstrm — APPROVED** [review]
Looks good to me. Matches schema as deployed.

**Comment by Dantemss** [comment]
Cool I'll send it to Review to be merged for next release or the one after

**Pull request merged**
