### PR TITLE
Upgrade node

### PR DESCRIPTION
**Pull request by TomWoodward**

### CODE REVIEW

**Comment by TomWoodward** [comment]
i could probably actually clean up some syntax and remove those defer calls in favor of setImmediate, i'm curious if CI passes though

**Comment by TomWoodward** [comment]
hmm probably it won't because CI runs in the container ` openstax/rex-web:CI ` that is pre-built....

**Comment by TomWoodward** [comment]
Fsevents version is causing error starting app in development at least on mac

**Review by PiotrKozlowski — COMMENTED** [review]
I think `setImmediate` is okay to use in tests so we should replace all `await new Promise(defer);` with it?

There is some `yarn test:build` error about rangy:
`Rangy is not supported in this environment. Reason: Rangy can only run in a browser`

**Comment by TomWoodward** [comment]
@PiotrKozlowski yes i agree i'm going to go back and get rid of the defer calls

i think the rangy thing might have always been there, if not i might have to add some more mocks for it.

right now i'm working on a build error i didn't notice because it wasn't breaking the unit tests, something about fsevents, it looks like i'll have to upgrade react-scripts to fix it

**Comment by TomWoodward** [comment]
closing for now because of major issue with react-intl. they have removed the ability to use html in translations without supporting code in the implementation. having different html per translation is a crucial use case for us, so this isn't really acceptable. we'll have to migrate internationalization systems before proceeding on this

**Pull request closed without merging**
