### PR TITLE
Add styles for coreq-skills section

### PR DESCRIPTION
**Pull request by PiotrKozlowski**
for: https://github.com/openstax/unified/issues/1208

Edit:
It can be tested on https://rex-web-issue-1208-4h0cytptsm0.herokuapp.com/books/9b08c294-057f-4201-9f48-5d6ad992740d@latest/pages/d0a86917-6447-4b49-bed1-efb5c352cc77?archive=https://archive-katalyst01.cnx.org

~~I think for now there is no other way to test it in REX than creating a new node in main content with html for coreq section:~~
`<section data-depth="1" id="eip-841" class="coreq-skills"><h3 class="os-title"><span class="os-title-label">COREQUISITE SKILLS</span></h3><h3 data-type="title">Linear Functions </h3><section data-depth="2" id="eip-744"><h4 data-type="title">Student Learning Objectives</h4><ul id="eip-266"><li>Find the slope of a line (IA 3.2.1)</li><li>Find an equation of the line given two points (IA 3.3.3)</li></ul></section></section>`

### CODE REVIEW

**Review by janKozie1 — COMMENTED** [review]
The snippet you provided looks good. I tried copy-pasting the dom node from https://content01.cnx.org/contents/GCQ6yUnf@4.1:da7oJVBL@7/4-1-Linear-Functions that contains the coreq skills and some text looks a bit small.

Is the content different from what would normally be received? (lacks some styles?)

Screenshot from 2020-08-10 19-34-25

**Comment by PiotrKozlowski** [comment]
@janKozie1 Let's wait for baked and updated content https://openstax.slack.com/archives/C8V1XET1R/p1597150109279400

**Comment by PiotrKozlowski** [comment]
It can be tested on https://rex-web-issue-1208-4h0cytptsm0.herokuapp.com/books/9b08c294-057f-4201-9f48-5d6ad992740d@latest/pages/d0a86917-6447-4b49-bed1-efb5c352cc77?archive=https://archive-katalyst01.cnx.org

**Comment by janKozie1** [comment]
Screenshot from 2020-08-11 19-13-10
is this okay? The` <h5> `have smaller computed font size than the text next to them and design shows them being around the same size. 

Also those are displayed in new lines 
Screenshot from 2020-08-11 19-18-17

I'm not sure if this PR is only for styling the wrapper of coreq and its title or it should adjust those things too,

**Comment by PiotrKozlowski** [comment]
Let's wait for a response: https://openstax.slack.com/archives/C8V1XET1R/p1597234746013200
I have nothing against styling these two, but I don't know what other elements might be in this section so it might ended with half styled content in this section

**Review by janKozie1 — APPROVED** [review]

**Pull request merged**
