### PR TITLE
make some sw errors warnings in sentry

### PR DESCRIPTION
**Pull request by TomWoodward**
for: openstax/unified#1509

### CODE REVIEW

**Review by PiotrKozlowski — APPROVED** [review]

**Comment by TomWoodward** [comment]
You can actually throw anything in javascript so it's probably better to
leave it as any even if we always use the error type

**Comment by PiotrKozlowski** [comment]
I know, I was thinking of making sure that we throw only what we really want to throw, but I don't think it should be implemented in this PR or implemented at all

**Comment by TomWoodward** [comment]
casting doesn't do that, because if you did like `throw 'asdf'` then your catch is going to get a string, casting it to an error is just going to mask errors. we'd have to make an error constructor that takes `any` and returns errors or converts them if they're not errors similar to how we did for the application errors, but i believe sentry already has that logic in their client so i don't think it makes sense to do it on our end as well

**Comment by PiotrKozlowski** [comment]
I was thinking of something like this:
```ts
try {
  await someAsyncFunction().catch(convertErrorToOurErrorTypeAndThrowItAgain) 
} catch (e) {
  const error = <OurErrorThrownByOurLongNamedFunction>e;
  ...
}
```

**Pull request merged**
