### PR TITLE
map spanish books

### PR DESCRIPTION
**Pull request by jivey**
for: https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/1909

### CODE REVIEW

**Comment by bethshook** [comment]
are you going to add the other maps to this PR or make separate ones?

**Comment by jivey** [comment]
Didn't mean to actually open this yet, yeah I can add the rest here, probably easier to test all at once?

**Comment by jivey** [comment]
@bethshook okay I went through the list and I think just the statistics books were missing, here's my understanding: Calculus volumes are already mapped, Precalculus is supposed to point to itself, and this PR updates the Statistics and Chem AF 2e mappings. Are there any other mappings I'm missing?

**Comment by jivey** [comment]
@bethshook Though maybe something missing is that Calculus says "shares two chapters with volume two" so maybe that needs to be mapped, but it doesn't say which 🤔

**Comment by bethshook** [comment]
Re Calculus, believe that should be working automatically, assuming IDs are the same. I think you're just missing Física Universitaria Volumen 1-3.

**Review by bethshook — APPROVED** [review]
I haven't checked the canonical links themselves but the maps look good

**Pull request merged**
