### PR TITLE
Change publish_date to latest revision date in Attribution copyrights

### PR DESCRIPTION
**Pull request by PiotrKozlowski**
for: https://github.com/openstax/unified/issues/320

### CODE REVIEW

**Review by TomWoodward — CHANGES_REQUESTED** [review]
@PiotrKozlowski did you try this? as far as i can see the cms doesn't have a `revised` field. the card specifies that we should use the `Revision field in Archive`, which does have a `revised` field. seems like your changes to `src/app/content/utils.ts`, `src/test/mocks/osWebLoader.ts`, and `src/gateways/createOSWebLoader.ts` are not needed and the change in `src/app/content/types.ts` should be on `ArchiveBook`

**Comment by PiotrKozlowski** [comment]
@TomWoodward I've moved `revised` to `ArchiveBook`. I've implemented this to `OsWebBook` because I was going from `console.log` in `Attribution.tsx` up until I've updated all files.
I'm not familiar yet with differences between `ArchiveBook` and `OSWebBook`

**Comment by TomWoodward** [comment]
@PiotrKozlowski OSWeb is the cms, here is an example book https://rex-web.herokuapp.com/apps/cms/api/v2/pages/?type=books.Book&fields=cnx_id,authors,publish_date,cover_color&slug=calculus-volume-1 it generally has book metadata having to do with the display (like the theme color) or navigation (like the book slug in the url) so that we can be consistent with openstax.org (managed by the osweb cms)

archive has the actual book content for example https://rex-web.herokuapp.com/contents/8b89d172-2927-466f-8661-01abc7ccdba4@12.1 it has things like the table of contents, what license the book is published under, a history of changes, things like that

**Review by TomWoodward — APPROVED** [review]
passing to qa

**Pull request merged**
